# Minimal hardened postgresql.conf for the stack example.
# Mounted by voodu inside the postgres container at
# /etc/postgresql/postgresql.conf. Postgres reads it at boot
# via the `-c config_file=...` flag set in voodu.hcl.

# --- Connections -----------------------------------------------------------

listen_addresses = '*'
port             = 5432
max_connections  = 100

# --- Memory ---------------------------------------------------------------

shared_buffers       = 256MB
effective_cache_size = 768MB
work_mem             = 4MB

# --- WAL ------------------------------------------------------------------

wal_level   = replica
fsync       = on
synchronous_commit = on

# --- Logging --------------------------------------------------------------

log_min_duration_statement = 200ms
log_connections            = on
log_disconnections         = on
log_line_prefix            = '%t [%p]: db=%d,user=%u,client=%h '

# --- Locale --------------------------------------------------------------

datestyle  = 'iso, mdy'
timezone   = 'UTC'
lc_messages = 'C'
