version: 2

project_name: voodu

before:
  hooks:
    - go mod tidy

builds:
  - id: voodu
    main: ./cmd/cli
    binary: voodu
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: voodu-controller
    main: ./cmd/controller
    binary: voodu-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: voodu
    ids:
      - voodu
    name_template: "voodu_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: voodu-controller
    ids:
      - voodu-controller
    name_template: "voodu-controller_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: thadeu
    name: clowk-voodu
  draft: false
  prerelease: auto
