package procfile

import (
	"fmt"
	"strconv"
	"strings"
)

// ToHCL renders the same transform as ToManifests into a `.voodu` HCL
// file for `vd apply -f Procfile --eject`. The output is a faithful
// starting point an operator can own: it matches runtime behavior
// (shell-wrapped commands, PORT env + ports, env_from, restart) and
// appends a commented `ingress` stub so adding a domain + TLS is a
// one-edit decision (runtime mode never routes).
func ToHCL(procs []Process, opts Options) (string, error) {
	if opts.Scope == "" {
		return "", fmt.Errorf("scope is required")
	}

	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by `vd apply -f Procfile --eject`.\n")
	fmt.Fprintf(&b, "# App-wide config vars (Heroku config:set) → scope-level config,\n")
	fmt.Fprintf(&b, "# which every process below inherits automatically:\n")
	fmt.Fprintf(&b, "#   vd config %s set KEY=value\n\n", opts.Scope)

	port := BasePort
	firstHTTP := ""

	for _, p := range procs {
		if p.IsRelease() {
			fmt.Fprintf(&b, "job %q %q {\n", opts.Scope, p.Type)
			fmt.Fprintf(&b, "  command = %s\n", hclStringList(shellWrap(p.RawCommand)))
			fmt.Fprintf(&b, "}\n\n")

			continue
		}

		portStr := strconv.Itoa(port)
		port++

		if firstHTTP == "" {
			firstHTTP = p.Type
		}

		fmt.Fprintf(&b, "deployment %q %q {\n", opts.Scope, p.Type)
		fmt.Fprintf(&b, "  command  = %s\n", hclStringList(shellWrap(p.RawCommand)))
		fmt.Fprintf(&b, "  replicas = 1\n")
		fmt.Fprintf(&b, "  env = {\n")
		fmt.Fprintf(&b, "    PORT = %s\n", hclString(portStr))
		fmt.Fprintf(&b, "  }\n")
		fmt.Fprintf(&b, "  ports    = [%s]\n", hclString(portStr))
		fmt.Fprintf(&b, "  restart  = %s\n", hclString(RestartPolicy))
		fmt.Fprintf(&b, "}\n\n")
	}

	// Commented ingress stub — host/TLS is opt-in and the operator
	// picks which process is routable (no convention to guess from).
	stubProc := firstHTTP
	if stubProc == "" {
		stubProc = "web"
	}

	fmt.Fprintf(&b, "# Expose a process over a domain with TLS — uncomment + edit:\n")
	fmt.Fprintf(&b, "# ingress %q %q {\n", opts.Scope, stubProc)
	fmt.Fprintf(&b, "#   host = \"app.example.com\"\n")
	fmt.Fprintf(&b, "#   tls { enabled = true }\n")
	fmt.Fprintf(&b, "# }\n")

	return b.String(), nil
}

// hclStringList renders a Go string slice as an HCL list literal.
func hclStringList(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = hclString(s)
	}

	return "[" + strings.Join(quoted, ", ") + "]"
}

// hclString quotes a value as an HCL string literal. Beyond the usual
// backslash/quote escaping, it neutralizes `${` → `$${` and `%{` → `%%{`
// so a command containing those sequences (rare, but `${FOO}` shell
// expansion does occur) is emitted as a literal instead of an HCL
// interpolation/template directive.
func hclString(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\t", `\t`,
		`${`, `$${`,
		`%{`, `%%{`,
	)

	return `"` + r.Replace(s) + `"`
}
